### ISSUE TITLE
Can't find camera_model package

### ISSUE THREAD

**Issue by name8997** [levenberg/2D-3D-pose-tracking#2]
Hello 

I have errors during Build AFM line detection to catkin_make
Below is my environment and excuted command line

- Ubuntu 18.04
- python 2.7, CUDA 10.2, pytorch 1.4.0, opencv 3.2.0

```
    cd catkin_ws/src/afm/scripts
    pip install -r requirements.txt
    pip install torch torchvision
    cd lib
    make
    cd ../../../../
    catkin_make
```
Error Log

Base path: /home/dxp/2D-3D-pose-tracking/catkin_ws
Source space: /home/dxp/2D-3D-pose-tracking/catkin_ws/src
Build space: /home/dxp/2D-3D-pose-tracking/catkin_ws/build
Devel space: /home/dxp/2D-3D-pose-tracking/catkin_ws/devel
Install space: /home/dxp/2D-3D-pose-tracking/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/dxp/2D-3D-pose-tracking/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/dxp/2D-3D-pose-tracking/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.20
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - afm
-- ~~  - initialization_publisher
-- ~~  - map_fusion
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'afm'
-- ==> add_subdirectory(afm)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found OpenCV: /usr (found suitable version "3.2.0", minimum required is "3.2.0") 
-- afm: 1 messages, 0 services
-- +++ processing catkin package: 'initialization_publisher'
-- ==> add_subdirectory(initialization_publisher)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Could NOT find camera_model (missing: camera_model_DIR)
-- Could not find the required component 'camera_model'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "camera_model" with
  any of the following names:

    camera_modelConfig.cmake
    camera_model-config.cmake

  Add the installation prefix of "camera_model" to CMAKE_PREFIX_PATH or set
  "camera_model_DIR" to a directory containing one of the above files.  If
  "camera_model" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  initialization_publisher/CMakeLists.txt:9 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dxp/2D-3D-pose-tracking/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/dxp/2D-3D-pose-tracking/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:1622: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

Please give me solution... how to import camera_model package...

**Comment by levenberg** [comment]
Hi @name8997 ,

Thank you for reporting this bug. **camera_model** package is from VINS-Mono and it is a dependency for **map_fusion** package. If you only build **afm**, there won't be any issue.

I have revised the readme file for building VINS-Mono first. If VINS-Mono has been built, **camera_model ** package can be found.

**Comment by name8997** [comment]
I solved it!!

Thank you for help.
